name: Docker Build and Release
on: [ push ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tipp: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  # Tipp: Für mvn package muss -Dcheckstyle.skip=true angehängt werden, da die Unternehmens-pptx nen http aufruf in der metadata hat
  GITHUB_ACCESSTOKEN: ${{ secrets.ACCESSTOKEN_PET }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
        cache-dependency-path: '**/pom.xml'
  
    - name: Compile, build and push
      run: |
        #### AUFGABE COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build
        mvn clean package -Dcheckstyle.skip=true
        docker login ghcr.io -u rahelbauer -p $GITHUB_ACCESSTOKEN
        docker build -t ghcr.io/rahelbauer/pet-clinic:latest .
        docker push ghcr.io/rahelbauer/pet-clinic:latest
